### ISSUE TITLE
Sudo functions for Sparta testnet

### ISSUE THREAD

**Issue by mnaamani** [Joystream/substrate-node-joystream#10]
During testnet we need sudo key to performs following actions:

- Gracefully end election
- Disable/Enable council election from starting automatically
- Start an election
- Set a new council
- Set election parameters
- Set new runtime

**Comment by mnaamani** [comment]
done in #22

**Comment by siman** [comment]
@mnaamani  what do you think about adding such method to sudo `set_stage(stage_name: Vec<u8>, ends_at: BlockNumber)`?
