### ISSUE TITLE
use generic parameters to pass type information to encodable data types where possible.

### ISSUE THREAD

**Issue by mnaamani** [Joystream/substrate-node-joystream#16]
https://github.com/Joystream/substrate-node-joystream/blob/19a3ab77ced03d42eb76bd9612a297a723af1b2e/runtime/src/governance/election.rs#L134

With this https://github.com/paritytech/parity-codec/pull/40 merged, we should be able to fix that horrible thing.

**Comment by siman** [comment]
To be able to do this, first, we need to update to the latest Substrate, node, UI... Let's wait until they have something more stable. Recently I read that these libs again are incompatible.

**Comment by mnaamani** [comment]
Yeah, I think also the node-template is being moved into mainline substrate repo also. I'm not sure if that means the substrate-up utilities will no longer be maintained. Should we switch over? I think it would be easier to stay up to date with breaking changes. I already forked substrate into our org.
