### ISSUE TITLE
ARMv7 cross compile builds

### ISSUE THREAD

**Issue by mnaamani** [Joystream/substrate-node-joystream#49]
Unfortunately it seems at the current time, trying to cross compile the node binary for ARMv7 architecture is not possible. There is a dependency on a package [clear_on_drop](https://github.com/cesarb/clear_on_drop) that is failing to build for specified target `armv7-unknown-linux-gnueabihf` and instead is trying to build for `x86_64-unknown-linux-gnu` (the host machine running the build). This may be due to the fact that the package has some assembly code specifically for that architecture. I imagine trying to compile on an armv7 host will also fail.

```
error: failed to run custom build command for `clear_on_drop v0.2.3`
process didn't exit successfully: `/home/mokhtar/Substrate/node/target/release/build/clear_on_drop-95166d2e2955f406/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("arm-linux-gnueabihf-gcc")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "arm-linux-gnueabihf-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-o" "/home/mokhtar/Substrate/node/target/release/build/clear_on_drop-cf53e16e107388be/out/src/hide.o" "-c" "src/hide.c"
cargo:warning=arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-m64’
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "arm-linux-gnueabihf-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-o" "/home/mokhtar/Substrate/node/target/release/build/clear_on_drop-cf53e16e107388be/out/src/hide.o" "-c" "src/hide.c" with args "arm-linux-gnueabihf-gcc" did not execute successfully (status code exit code: 1).

', /home/mokhtar/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.26/src/lib.rs:2295:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

host configuration:
```
Ubuntu 14.04
cross compiler: arm-linux-gnueabihf-gcc-4.8

rustup:
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

armv7-unknown-linux-gnueabihf
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.32.0 (9fda7c223 2019-01-16)
```

Ref guides for setting up cross compiling setup:
[openssl](https://stackoverflow.com/questions/37375712/cross-compile-rust-openssl-for-raspberry-pi-2#37378989) - remember to clear the ARCH,CC,MACHINE env variables before proceeding to cargo build
[armv7](https://hackernoon.com/compiling-rust-for-the-raspberry-pi-49fdcd7df658)

**Comment by mnaamani** [comment]
From the clear_on_drop README: 

> This crate has three mechanisms which prevent these unwanted optimizations, selected at compile time via cargo features.

Maybe we can get around the problem if we can configure the third mechanism.

> The third mechanism is a fallback, which attempts to confuse the optimizer through the use of atomic instructions. It should not be used unless necessary, since it's less reliable. It is enabled by the no_cc feature, works on stable Rust, and does not need a C compiler.

**Comment by mnaamani** [comment]
On a second try it was successful.
I had to clear the env variables, CC, ARCH, and MACHINE setup to cross-compile openssl in guide linked to previously.

Added the build to the releases page.

**Comment by sjsqd** [comment]
A few notes:
- This runs on a Raspberry Pi 3 B running Raspbian
- This will not run on an Orange Pi Prime (running Armbian). 

CPU use on RPI during sync is about 100% on a single core. Once it's fully synced I'll share some stats regarding CPU use.

**Comment by sjsqd** [comment]
I'm now fully sync'd and CPU use has dropped to ~10% on one core and memory use is at about 10%.
Will update after 48 hours if it runs well.

**Comment by mnaamani** [comment]
Thanks for feedback @sjsqd 

I think what you are seeing is common for any platform actually, while a node is syncing the CPU utilization will be high as it is performing a lot of validation of blocks and executing transactions in a short period of time.

Great that you got a Raspberry Pi running on the network! Looking forward to hear more on how it performs over time.

**Comment by sjsqd** [comment]
Just to update after about 48 hours of uptime the full node is running well with 8 peers. I'm sitting at 0.2-4% CPU & about 30% memory use.
