### ISSUE TITLE
Sparta network down.

### ISSUE THREAD

**Issue by bwhm** [Joystream/substrate-node-joystream#50]
On the 29th of March, all nodes went down with this error message:
```
Thread 'ImportQueueWorker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x5ef2a145ff5027f112393fd2266bfdd3f230abf7079985161df61f6b9dd21da9"', src/libcore/result.rs:1009

This is a bug. Please report it at:

	https://www.joystream.org
```

**Comment by mnaamani** [comment]
Relevant Links about the bug:

Bug: https://github.com/paritytech/substrate/issues/1733

Fixes:
https://github.com/paritytech/trie/pull/12
https://github.com/paritytech/substrate/pull/2130

**Comment by mnaamani** [comment]
In upcoming testnet we updated to latest substrate v1.0.0 so this issue can be closed.
