### ISSUE TITLE
Show correct format for Authority key

### ISSUE THREAD

**Issue by mnaamani** [Joystream/substrate-node-joystream#53]
When running a validator the authority key (ed25519) is logged: 

`Using authority key 5HY3LPr.....` 

The address is not using new encoding format. The to_ss58check() on the Pair is using old encoding.

Update to use : https://github.com/paritytech/substrate/blob/5240bc1fd0b4201384c2c55c9759fd3d7eeb2d0e/core/primitives/src/crypto.rs#L255

**Comment by mnaamani** [comment]
If its totally different, remember our UI generates addresses for Ed25519 addresses.
latest polkadot/keyring supports Ed25519 and Sr25519. Maybe you have to specify what crypto primitive to use when loading the json file. (I'm not sure it is encoded or keyring knows how to determine the correct type)

**Comment by mnaamani** [comment]
Our latest UI will supports this yes.

Is it necessary to generate the key in the UI? Why not just generate it in the storage node. As far as I can recall it is only the storage node that needs to sign and send transactions with this key?

**Comment by jfinkhaeuser** [comment]
It's for the member account - I can't transfer currency to the storage node account without the member account imported, at least during the signup phase.

**Comment by mnaamani** [comment]
Oh I didn't realize you designed the signup process to all happen in the storage node. Makes sense.

**Comment by jfinkhaeuser** [comment]
That's what we discussed :)

**Comment by mnaamani** [comment]
Fixed in https://github.com/Joystream/substrate-node-joystream/pull/57
