### ISSUE TITLE
Compile Docker image

### ISSUE THREAD

**Issue by sjsqd** [Joystream/substrate-node-joystream#60]
As discussed on the Telegram channel (I'm S J) I'll be trying to compile the node into a docker image.

I have limited experience with Docker, but if it works I'll be happy to share it.

**Comment by bwhm** [comment]
Great!
$50 bounty in monero if you are successful.

Note that you have to document the steps so we can reproduce it!

**Comment by mnaamani** [comment]
There is an old docker file in here https://github.com/Joystream/docker-files/blob/master/rust-wasm/Dockerfile It may or not be useful just sharing. Also wouldn't hurt to look at some docker files in the upstream Substrate repo for some ideas

**Comment by mnaamani** [comment]
@bwhm the bounty will go to @suda for implementing the docker image.

Thanks @sjsqd for at least starting the ball rolling. Perhaps you can try the one merged now if you need a docker image in the future.

**Comment by mnaamani** [comment]
@suda please see here about how you can share your address for the bounty payout: https://github.com/Joystream/helpdesk/blob/master/README.md#incentives-3

**Comment by suda** [comment]
@mnaamani done! Updated the memo field and added the address to the PR description: https://github.com/Joystream/substrate-node-joystream/pull/72
