### ISSUE TITLE
$100 Bounty for a working Windows binary 

### ISSUE THREAD

**Issue by bwhm** [Joystream/substrate-node-joystream#62]
As we have not been able to produce a binary for windows that syncs, we are offering a $100 bounty for anyone that can assist us to build a working one. Produce a script, or guide us how to set the correct build environment.

1. It must be built from the [v1.0.0](https://github.com/Joystream/substrate-node-joystream/releases/tag/v1.0.0) release tag.
2. After setting the correct environment, `./build-runtime.sh && cargo build --release` should produce the wanted result.

It is ok if the users still has to go through the extra steps as outlined in the "hidden" windows instructions [here](https://raw.githubusercontent.com/Joystream/helpdesk/master/roles/validators/README.md).

**Comment by mnaamani** [comment]
Bounty was opened to address this issue: https://github.com/Joystream/substrate-node-joystream/issues/61 which is resolved, but I think it still makes sense to get a build working with latest rust stable compiler (v1.34.0)

**Comment by mnaamani** [comment]
We don't have a windows build for latest release so maybe this is relevant. Closing and if a new bounty is created we can open a separate issue.
