### ISSUE TITLE
Validator ranking doesn't consider slashed tokens

### ISSUE THREAD

**Issue by bwhm** [Joystream/substrate-node-joystream#63]
If your `validator` has been slashed, it is still ranked by the number of tokens initially bonded.

**Comment by mnaamani** [comment]
By ranking are you referring to the order of the validators list in first column  on the 'validators overview' page?

That is just the initial order of the set created every era. As far as I know the Aura consensus algorithm just selects validators in a round-robin fashion for being the block producer. Actual amount staked doesn't appear to affect this selection process. I'm pretty sure reward is also fix amount for all validators, not proportional to individual stake. (However it is dynamic and recalculated every era when the new validator set is selected - based on the lowest stake)

**Comment by bwhm** [comment]
> By ranking are you referring to the order of the validators list in first column on the 'validators overview' page?

Yes

> That is just the initial order of the set created every era. 

I don't think this is correct,  ref what I saw with #130 (may have been fixed).
When I nominated the `validator` there, he "jumped" up in the rank to the slot he should have if ordered by `validator-stash` + `nominater-stash` bonded tokens.

> Actual amount staked doesn't appear to affect this selection process. I'm pretty sure reward is also fix amount for all validators, not proportional to individual stake.

I think this is correct though.

**Comment by mnaamani** [comment]
No longer relevant, this issue is about a much older version of both the ui and substrate.
Closing.
