### ISSUE TITLE
WIP: KB for Joystream Node Athens Release

### ISSUE THREAD

**Issue by sqyuid** [Joystream/substrate-node-joystream#71]
<details>
  <summary>Document scope/objectives:</summary>

 -	This document currently deals with running a Joystream Node on the Athens testnet (either as a regular node or as a validator role)
-	This document does not currently extend to dealing with UI issues (such as staking/bonding). It may do so at a later stage.
-	This document does not extend to running storage or other nodes; should those nodes have similar documents they will be linked here.
-	This document currently deals with pre-compiled binaries and doesn’t include information pertaining to compiling software.
-	Transfer knowledge from various sources to a common place
-	Improve & contribute to search engine readability of the project
-	Provide limited technical information on how and why some errors occur
-	Allow users to be more self-sufficient and help to reduce the time required to help users with common technical issues.
### Revisions:
-	As newer versions of Joystream are released, some errors/solutions may no longer be useful and will be excluded from this document in the future. A subsection will be created for this eventually so that non-relevant knowledge is still available for users of other projects.

</details>

<details>
<summary>Some useful questions to answer before troubleshooting any issues:</summary>

-	**Are you running your node on a domestic/home internet connection or from a data center/VPS server?**
Home internet connections, in general, have lower peer connectivity. It is highly recommended that if operating a node at home that you use a reliable ethernet connection and avoid things like WiFi. Some domestic internet providers also block, or throttle certain internet traffic, and this may cause connectivity issues.
-	**Is your node behind a firewall (such as on your computer, firewall, ISP, datacenter)?**
Firewalls if not configured appropriately may cause connectivity issues. You may find that adjusting your firewall settings can help to improve your node’s health. Changing firewall settings should only be done if you're confident with you 
-	**How long have you left the node running?**
Joystream’s node utilizes technology that helps it to “discover” other nodes. It can take some time (5-30 minutes) for this process to fully happen. If you’re having issues connecting to other nodes, slow sync speed or other issues, try to leave the node running for a while before changing settings.
</details>

### Current issues & solutions:
- **Low peer count or no connected peers.** (GitHub issue: #68 )
_Current peer counts range from 1-10+ peers and this number depends on a number of external factors._
_Some users have found the following launch options to be helpful in improving node connectivity. The technical explanation for this is that Joystream is attempting to connect to non-Joystream nodes within the Substrate network and it’s default connection limits have caused some issues. It’s possible this issue will be improved upon in later versions._
`./joystream-node --in-peers 200 --out-peers 200`
_Some users have found that manually specifying a port for the node can be helpful in improving node connectivity. In the below example, the default port for Joystream has been manually specified; using other port numbers may cause issues._
		`./joystream-node –port 30333`
- **“Stuck” node for an extended period of time (Node stops syncing and remains at 0 peers but otherwise launches and runs fine)**
Some users have found that restarting the node can fix connectivity issues.
Some users have found that wiping the blockchain can help to fix a “stuck” node.
`./joystream-node revert`
This command will revert the blockchain to its last known “good block,” but will not delete any keys generated by the node.
If the revert command does not work, then you can try the purge-chain command:
`./joystream-node purge-chain`
This command will entirely wipe the current blockchain from your node, but will not delete any keys generated by the node

- **Node will not list on the Joystream/Polkadot Telemetry page** (https://telemetry.polkadot.io/#/Joystream%20Testnet%20v2)
Some releases of Joystream, such as the Raspberry Pi/ARM and Windows binaries do not successfully connect to the Telemetry server by default. Some users have found that manually specifying the telemetry server as a launch option can help with this issue.
	`./joystream-node  --telemetry-url ws://telemetry.polkadot.io:1024/`

- **Validator Node that has been successfully accepted by the network and creating blocks does not generate any Joystream tokens when creating blocks**
_Joystream is currently in active development and the reward structure is still being experimented with. It may take some time for incentives to become fully fleshed out._

### Common error messages & explanations:
-	Frequent **“banning a node”** or _“Banning PeerID”_ messages (these can usually be safely ignored)
_These messages occur because Joystream is based on Substrate, and Joystream currently will “discover” nodes that are nodes on other projects. These messages can be safely ignored._
	

### Rare error messages & solutions:
-	`DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col6, col8, col3, col2, col5, col1, col0, col4, attempting repair`
This error message likely occurs due to a database problem with Joystream’s blockchain stored on your device. You can try to fix this error by running these commands:
`./joystream-node revert`
This command will revert the blockchain to its last known “good block,” but will not delete any keys generated by the node.
If the revert command does not work, then you can try the purge-chain command:
`./joystream-node purge-chain`
This command will entirely wipe the current blockchain from your node, but will not delete any keys generated by the node

**Comment by bwhm** [comment]
Hey @sjsqd .

This is much appreciated help! Please open an issue in the [helpdesk](https://github.com/Joystream/helpdesk) repo, and refer to this!

**Comment by mnaamani** [comment]
We will be deprecating this repo soon, so any valuable knowledge from this issue as recommended in https://github.com/Joystream/helpdesk/issues/26 should be moved into the helpdesk [trouble shooting section](https://github.com/Joystream/helpdesk/tree/master/roles/validators#troubleshooting)
